#[cfg(feature = "sync")]
pub mod auth_client;
pub mod clock;
#[cfg(feature = "sqlite")]
pub mod db;
#[cfg(feature = "sqlite")]
pub mod entity;
pub mod exif_reader;
#[cfg(feature = "sqlite")]
pub mod mapper;
#[cfg(feature = "sync")]
#[cfg(feature = "test-support")]
pub mod memory;
pub mod photo_store;
pub mod sealer;
#[cfg(feature = "sqlite")]
pub mod sqlite_entry_repository;
#[cfg(feature = "sqlite")]
mod sqlite_hydrate;
pub mod sync_client;
#[cfg(feature = "sqlite")]
pub mod sync_outbox;
pub mod thumbnailer;
pub mod vault_sealer;
#[cfg(feature = "sqlite")]
pub mod vault_store;
#[cfg(feature = "sync")]
pub mod vault_sync;
pub mod xchacha_sealer;

#[cfg(feature = "sync")]
pub use auth_client::AuthClient;
pub use clock::SystemClock;
pub use exif_reader::KamadakExifReader;
#[cfg(feature = "sync")]
#[cfg(feature = "test-support")]
pub use memory::{FixedClock, InMemoryEntryRepository};
pub use photo_store::FilePhotoStore;
pub use sealer::PlaintextSealer;
#[cfg(feature = "sqlite")]
pub use sqlite_entry_repository::SqliteEntryRepository;
pub use sync_client::SyncClient;
#[cfg(feature = "sqlite")]
pub use sync_outbox::SyncOutbox;
pub use thumbnailer::ImageThumbnailer;
pub use vault_sealer::VaultSealer;
#[cfg(feature = "sqlite")]
pub use vault_store::{SqliteDeviceSlotStore, SqliteVaultStore};
#[cfg(feature = "sync")]
pub use vault_sync::VaultSync;
pub use xchacha_sealer::XChaChaSealer;
