[package]
name = "leafypuff-core"
version.workspace = true
license.workspace = true
edition = "2024"

[lib]
crate-type = ["rlib"]

[features]
default = []
test-support = []

[dev-dependencies]
tokio = { workspace = true }
uuid = { workspace = true }

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
