[package]
name = "leafypuff-api"
version.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
leafypuff-core = { path = "../core" }
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
